config/routes.rb
MusicApp::Application.routes.draw do

  get "/search" => "search#create"
  post "/search" => "search#create"
  
  root              :to => 'static_pages#home', :as => 'home'
  match '/help',    :to => 'static_pages#help'
  match '/about',   :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'

  devise_for :users, :skip => [:sessions, :registrations, :passwords]
  
  as :user do
    get '/password' => 'devise/passwords#new', :as => :reset_password
    post '/password' => 'devise/passwords#create',:as => :reset_password
    get 'password/edit' => 'devise/passwords#edit', :as => :password_edit
    put '/password' => 'devise/passwords#update'

    get '/login ' => 'devise/sessions#new', :as => :login
    get '/login' => 'devise/sessions#new', :as => :new_user_session    
    post '/login' => 'devise/sessions#create', :as => :login
    delete '/logout' => 'devise/sessions#destroy', :as => :logout
    
    get '/singup' => 'devise/registrations#new', :as => :signup
    post '/singup' => 'devise/registrations#create', :as => :signup
    get '/edit' => 'devise/registrations#edit', :as => :edit_user
    delete '/users' => 'devise/registrations#destroy', :as => :delete_user
    put ':id' => 'devise/registrations#update', :as => :update_user

  end
             
  resources :users, :only => :show, :path => '/' do
    resources :events, :only => [:new, :create, :edit, :update, :show, :index]
  end
  
  resources :events, :only => :index
  get "event/show_image" => "events#show_image"
 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  skip_before_filter :authenticate_user!
  
  def home
    @user = current_user
    unless @user.nil?
      @events = @user.events
      if user_signed_in?
        render template: "events/index"
      else
        render :home
      end
    else
      render :home
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  Not implemented yet
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Not implemented yet.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
    Not implemented Yet
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Socialife</h1>

  <h2>
    This is the site where you find all
    <a href=<%=home_url%> >Your favorite events</a>
    in one place.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>