config/routes.rb
MusicApp::Application.routes.draw do

  get "/search" => "search#create"
  post "/search" => "search#create"
  
  root              :to => 'static_pages#home', :as => 'home'
  match '/help',    :to => 'static_pages#help'
  match '/about',   :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'

  devise_for :users, :skip => [:sessions, :registrations, :passwords]
  
  as :user do
    get '/password' => 'devise/passwords#new', :as => :reset_password
    post '/password' => 'devise/passwords#create',:as => :reset_password
    get 'password/edit' => 'devise/passwords#edit', :as => :password_edit
    put '/password' => 'devise/passwords#update'

    get '/login ' => 'devise/sessions#new', :as => :login
    get '/login' => 'devise/sessions#new', :as => :new_user_session    
    post '/login' => 'devise/sessions#create', :as => :login
    delete '/logout' => 'devise/sessions#destroy', :as => :logout
    
    get '/singup' => 'devise/registrations#new', :as => :signup
    post '/singup' => 'devise/registrations#create', :as => :signup
    get '/edit' => 'devise/registrations#edit', :as => :edit_user
    delete '/users' => 'devise/registrations#destroy', :as => :delete_user
    put ':id' => 'devise/registrations#update', :as => :update_user

  end
             
  resources :users, :only => :show, :path => '/' do
    resources :events, :only => [:new, :create, :edit, :update, :show, :index]
  end
  
  resources :events, :only => :index
  get "event/show_image" => "events#show_image"
 
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  skip_before_filter :authenticate_user!
  
  def create
    @users = User.search(params[:search_keywords])
    @events = Event.search(params[:search_keywords])
              
    render :results
  end
  
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/results.html.erb
<% provide(:title, 'Search Results') %>
<h1>Results</h1>

<ul class="users">
  
  <% @events.each do |event| %>
    <li>
      <%= image_tag url_for(:controller => "events",
                            :action => "show_image",
                            :id => event.id), 
                            :size => "175x120" %>
                            
      <%= link_to event.title, user_event_url(event.user_id, event) %>
    </li>
  <% end %>
  <% @users.each do |user| %>
      <li>
        <%= gravatar_for user, size: 52 %>
        <%= link_to user.full_name, user %>
      </li>
  <% end %>
</ul>