config/routes.rb
MusicApp::Application.routes.draw do

  get "/search" => "search#create"
  post "/search" => "search#create"
  
  root              :to => 'static_pages#home', :as => 'home'
  match '/help',    :to => 'static_pages#help'
  match '/about',   :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'

  devise_for :users, :skip => [:sessions, :registrations, :passwords]
  
  as :user do
    get '/password' => 'devise/passwords#new', :as => :reset_password
    post '/password' => 'devise/passwords#create',:as => :reset_password
    get 'password/edit' => 'devise/passwords#edit', :as => :password_edit
    put '/password' => 'devise/passwords#update'

    get '/login ' => 'devise/sessions#new', :as => :login
    get '/login' => 'devise/sessions#new', :as => :new_user_session    
    post '/login' => 'devise/sessions#create', :as => :login
    delete '/logout' => 'devise/sessions#destroy', :as => :logout
    
    get '/singup' => 'devise/registrations#new', :as => :signup
    post '/singup' => 'devise/registrations#create', :as => :signup
    get '/edit' => 'devise/registrations#edit', :as => :edit_user
    delete '/users' => 'devise/registrations#destroy', :as => :delete_user
    put ':id' => 'devise/registrations#update', :as => :update_user

  end
             
  resources :users, :only => :show, :path => '/' do
    resources :events, :only => [:new, :create, :edit, :update, :show, :index]
  end
  
  resources :events, :only => :index
  get "event/show_image" => "events#show_image"
 
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href=<%=home_url%> >News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">  
  <div class="container">
    <button class = "btn btn-info btn-sm navbar-toggle" data-toggle = 
    "collapse" data-target = ".navHeaderCollapse" type="button">
            <span class = "icon-bar"></span>
            <span class = "icon-bar"></span>
            <span class = "icon-bar"></span>
    </button>
    <%= link_to "Socialife", home_path, id: "logo", class: "navbar-brand" %>
    
    <div class = "navbar-collapse collapse navbar-responsive-collapse 
    navHeaderCollapse">
    
      <ul class="nav navbar-nav pull-right">
       <form action="/search" method="post" class="navbar-form pull-left">
         <input type="text" placeholder="Search Here..." 
         style="width:200px" class="form-control" 
         name="search_keywords">
      
         <button type="button" class="btn btn-info btn-sm">
           <span class="glyphicon glyphicon-search"></span>
         </button>
       </form>
       <% if user_signed_in? %>
          <li class="active"><%= link_to "Notifications", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Events <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "My Events", user_events_url(current_user) %>
              </li>
              <li>
                <%= link_to "Create Event", new_user_event_url(current_user)%>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-user"></span>
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Profile", current_user %>
              </li>
              <li>
                <%= link_to "Settings", edit_user_url(current_user) %>
              </li>
              <li class="divider"></li>
              <li>
                <%= button_to 'Logout', logout_path, :method => :delete%>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Twitter Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', home_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_user_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sozialize" %></title>
      <metaname="description" content="<%=content_for? (:description) ? 
      yield(:description) : "Sozialize" %>">
       
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" %>
    <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css" %>
    <%= javascript_include_tag "application" %>
    
    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <%= render 'layouts/header' %>
    
    <div class="container">	  
        
      <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    </div>
    
      <%= render 'layouts/footer' %>
        
      <%= debug(params) if Rails.env.development? %>
      <%= debug(session) if Rails.env.development? %>
  </body>
</html>